#include "main.h"

extern pros::Controller master;

#define FLYWHEEL_FWD_BUTTON pros::E_CONTROLLER_DIGITAL_X
#define FLYWHEEL_BACK_BUTTON pros::E_CONTROLLER_DIGITAL_B
#define FLYWHEEL_STICK pros::E_CONTROLLER_ANALOG_RIGHT_Y

#define INTAKE_STICK pros::E_CONTROLLER_ANALOG_RIGHT_Y
#define INTAKE_BUTTON pros::E_CONTROLLER_DIGITAL_LEFT
#define DRIVE_FWD pros::E_CONTROLLER_ANALOG_LEFT_Y
#define DRIVE_TRN pros::E_CONTROLLER_ANALOG_LEFT_X

#define WIRELESS_RECIEVER_PORT 10